name: "CI - Test Templates"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            edgeactions: ./**/edgeactions/**
  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
        kvm: [true, false]
    steps:
      - uses: actions/checkout@v3

      - name: Disable KVM
        if: matrix.kvm == false
        run: sudo chmod 000 /dev/kvm

      - name: Smoke test for '${{ matrix.templates }}' (KVM=${{ matrix.kvm }})
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
      
